keepHatOnDeath = true
seasonalBagChance = 20
enableMobLoot = false
enableChestLoot = true
allowHatInHelmetSlot = false
chestNoneWeight = 200
chestCommonWeight = 15
chestUncommonWeight = 10
chestRareWeight = 5
chestEpicWeight = 1
entityNoneWeight = 200
entityCommonWeight = 20
entityUncommonWeight = 15
entityRareWeight = 10
entityEpicWeight = 5
