ServerEvents.recipes((event) => {

  event.smithing(
    'simplyswords:slumbering_lichblade',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'hmag:lich_cloth'
  )
  event.smithing(
    'simplyswords:enigma',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'l2complements:captured_wind'
  )
  event.smithing(
    'simplyswords:brimstone_claymore',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'hmag:burning_core'
  )
  event.smithing(
    'simplyswords:caelestis',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'celestial_core:midnight_fragment'
  )
  event.smithing(
    'simplyswords:ribboncleaver',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'minecraft:red_wool'
  )
  event.smithing(
    'simplyswords:dormant_relic',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'cataclysm:ancient_metal_ingot'
  )
  event.smithing(
    'simplyswords:watcher_claymore',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'minecraft:ender_eye'
  )
  event.smithing(
    'simplyswords:twisted_blade',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'hmag:sharp_fang'
  )
  event.smithing(
    'simplyswords:waxweaver',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_claymore',
    'the_bumblezone:super_candle'
  )
  event.smithing(
    'simplyswords:mjolnir',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_greathammer',
    'hmag:lightning_particle'
  )
  event.smithing(
    'simplyswords:frostfall',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_greathammer',
    'minecraft:packed_ice'
  )
  event.smithing(
    'simplyswords:hearthflame',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_greathammer',
    'nethersdelight:blackstone_blast_furnace'
  )
  event.smithing(
    'simplyswords:hiveheart',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_greathammer',
    'minecraft:bee_nest'
  )
  event.smithing(
    'simplyswords:soulkeeper',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_greathammer',
    'endrem:undead_soul'
  )
  event.smithing(
    'simplyswords:livyatan',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_greataxe',
    'minecraft:packed_ice'
  )
  event.smithing(
    'simplyswords:molten_edge',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_greataxe',
    'celestial_core:fire_essence'
  )
  event.smithing(
    'simplyswords:soulpyre',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_greataxe',
    'l2complements:soul_flame'
  )
  event.smithing(
    'simplyswords:arcanethyst',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_halberd',
    'minecraft:amethyst_shard'
  )
  event.smithing(
    'simplyswords:thunderbrand',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_halberd',
    'hmag:lightning_particle'
  )
  event.smithing(
    'simplyswords:icewhisper',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_halberd',
    'l2complements:hard_ice'
  )
  event.smithing(
    'simplyswords:stormbringer',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_longsword',
    'hmag:lightning_particle'
  )
  event.smithing(
    'simplyswords:toxic_longsword',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_longsword',
    'minecraft:fermented_spider_eye'
  )
  event.smithing(
    'simplyswords:emberblade',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_longsword',
    'hmag:burning_core'
  )
  event.smithing(
    'simplyswords:flamewind',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_glaive',
    'nethersdelight:propelplant_cane'
  )
  event.smithing(
    'simplyswords:decaying_relic',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_glaive',
    'minecraft:sculk'
  )
  event.smithing(
    'simplyswords:storms_edge',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_twinblade',
    'hmag:lightning_particle'
  )
  event.smithing(
    'simplyswords:stars_edge',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_twinblade',
    'celestial_core:light_fragment'
  )
  event.smithing(
    'simplyswords:wickpiercer',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_spear',
    'the_bumblezone:super_candle'
  )
  event.smithing(
    'simplyswords:shadowsting',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_spear',
    'celestial_core:midnight_fragment'
  )
  event.smithing(
    'simplyswords:tempest',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_chakram',
    'l2complements:storm_core'
  )
  event.smithing(
    'simplyswords:soulrender',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_scythe',
    'endrem:undead_soul'
  )
  event.smithing(
    'simplyswords:watching_warglaive',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_warglaive',
    'minecraft:ender_eye'
  )
  event.smithing(
    'simplyswords:soulstealer',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_sai',
    'endrem:undead_soul'
  )
  event.smithing(
    'simplyswords:bramblethorn',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_rapier',
    'minecraft:spore_blossom'
  )
  event.smithing(
    'simplyswords:whisperwind',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_katana',
    'l2complements:captured_wind'
  )
  event.smithing(
    'simplyswords:emberlash',
    'simplyswords:empowered_remnant',
    'simplyswords:runic_cutlass',
    'celestial_core:fire_essence'
  )

});