ServerEvents.tags('item', event => {
	// Get the #forge:cobblestone tag collection and add Diamond Ore to it
	// event.get('forge:cobblestone').add('minecraft:diamond_ore')

	// Get the #forge:cobblestone tag collection and remove Mossy Cobblestone from it
	// event.get('forge:cobblestone').remove('minecraft:mossy_cobblestone')
	
	event.removeAllTagsFrom('skilltree:copper_nugget')
	
	
	event.get('rad3:mortars')
		.add('kubejs:stone_mortar')
		.add('kubejs:iron_mortar')
		 
	event.get('farmersdelight:tools/pickaxes')
	.add('minecraft:iron_pickaxe')
	.add('minecraft:golden_pickaxe')
	.add('minecraft:diamond_pickaxe')
	.add('minecraft:netherite_pickaxe')
	
	event.get('forge:ash').add('bonfires:ash_pile')
	
	event.get('rad3:coin_quest')
		.add('kubejs:copper_coin')
		.add('kubejs:iron_coin')
		.add('kubejs:gold_coin')
		.add('kubejs:diamond_coin')
		
	event.get('rad3:coin_dimension')
		.add('kubejs:coin_aether')
		.add('kubejs:coin_undergarden')	
		.add('kubejs:coin_twilight')
		.add('kubejs:coin_bumblezone')	
		.add('kubejs:coin_icaria')
		.add('kubejs:coin_end')	
		.add('kubejs:coin_nether')
		
	event.get('rad3:coin_task')
		.add('kubejs:coin_gathering')
		.add('kubejs:coin_exploration')
		.add('kubejs:coin_monster')
		.add('kubejs:coin_magic')	

	event.get('rad3:coin_loot')
		.add('kubejs:coin_dungeon')
		.add('kubejs:coin_exploration')
		.add('kubejs:coin_gear')	

	event.get('rad3:artifact')
		.add('artifacts:flippers')
		.add('artifacts:steadfast_spikes')
		.add('artifacts:snowshoes')
		.add('artifacts:running_shoes')
		.add('artifacts:kitty_slippers')
		.add('artifacts:bunny_hoppers')
		.add('artifacts:aqua_dashers')
		.add('artifacts:pickaxe_heater')
		.add('artifacts:onion_ring')
		.add('artifacts:vampiric_glove')
		.add('artifacts:pocket_piston')
		.add('artifacts:fire_gauntlet')
		.add('artifacts:power_glove')
		.add('artifacts:feral_claws')
		.add('artifacts:digging_claws')
		.add('artifacts:chorus_totem')
		.add('artifacts:helium_flamingo')
		.add('artifacts:crystal_heart')
		.add('artifacts:antidote_vessel')
		.add('artifacts:obsidian_skull')
		.add('artifacts:cloud_in_a_bottle')
		.add('artifacts:charm_of_sinking')
		.add('artifacts:thorn_pendant')
		.add('artifacts:flame_pendant')
		.add('artifacts:shock_pendant')
		.add('artifacts:panic_necklace')
		.add('artifacts:cross_necklace')
		.add('artifacts:scarf_of_invisibility')
		.add('artifacts:anglers_hat')
		.add('artifacts:cowboy_hat')
		.add('artifacts:superstitious_hat')
		.add('artifacts:villager_hat')
		.add('artifacts:night_vision_goggles')
		.add('artifacts:snorkel')
		.add('artifacts:novelty_drinking_hat')
		.add('artifacts:plastic_drinking_hat')
		.add('artifacts:everlasting_beef')
		.add('artifacts:umbrella')
		.add('relics:amphibian_boot')
		.add('relics:aqua_walker')
		.add('relics:arrow_quiver')
		.add('relics:bastion_ring')
		.add('relics:blazing_flask')
		.add('relics:chorus_inhibitor')
		.add('relics:drowned_belt')
		.add('relics:elytra_booster')
		.add('relics:enders_hand')
		.add('relics:holy_locket')
		.add('relics:horse_flute')
		.add('relics:hunter_belt')
		.add('relics:ice_breaker')
		.add('relics:infinity_ham')
		.add('relics:ice_skates')
		.add('relics:jellyfish_necklace')
		.add('relics:leather_belt')
		.add('relics:magic_mirror')
		.add('relics:magma_walker')
		.add('relics:midnight_robe')
		.add('relics:rage_glove')
		.add('relics:reflection_necklace')
		.add('relics:roller_skates')
		.add('relics:shadow_glaive')
		.add('relics:space_dissector')
		.add('relics:spatial_sign')
		.add('relics:wool_mitten')
		.add('relics:spore_sack')
		
	event.get('rad3:healing_items')
		.add('roughtweaks:medkit')
		.add('roughtweaks:salve')
		.add('roughtweaks:plaster')
		.add('undergarden:blood_globule')
		.add('cataclysm:amethyst_crab_meat')
		.add('fruitsdelight:orange_jello')
		.add('fruitsdelight:melon_jelly') 
		.add('farmersdelight:mixed_salad') 
		.add('minecraft:enchanted_golden_apple') 
		.add('minecraft:golden_apple') 
		.add('fruitsdelight:orange_jelly') 
		.add('bosses_of_mass_destruction:crystal_fruit') 
		.add('hmag:cubic_nucleus') 
		.add('aether_redux:enchanted_blueberry_pie') 
		.add('fruitsdelight:orange_marinated_pork') 
		.add('fruitsdelight:orange_chicken') 
		.add('fruitsdelight:orange_juice') 
		.add('fruitsdelight:melon_jello') 
		.add('farmersdelight:fruit_salad') 
		.add('minecolonies:golden_bread') 
		.add('farmersdelight:melon_juice') 
		.add('landsoficaria:fruit_salad') 
		.add('roughtweaks:bandage')
		.add('roughtweaks:medkit_enchanted')
		.add('aether:healing_stone')
		.add('landsoficaria:healing_flask')
	
////END	
})