# Don't change this! Version used to track needed updates.
version = 0
biomeColorRain = true
biomeParticlesRadius = 32
mushroomSporeBiomes = [
    "minecraft:mushroom_fields"
]
mushroomSporeDensity = 5
fireflyBiomes = [
    "minecraft:swamp",
    "minecraft:mangrove_swamp"
]
fireflyDensity = 3
pollenBiomes = [
]
pollenDensity = 50
sculkDustBiomes = [
    "minecraft:deep_dark"
]
sculkDustDensity = 2