// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')

JEIEvents.hideItems(event => {
	// Hide items in JEI here
	// event.hide('minecraft:cobblestone')
    event.hide('occultism:raw_silver')
    event.hide('occultism:silver_ingot')
    event.hide('occultism:silver_nugget')
    event.hide('occultism:silver_block')
    event.hide('occultism:raw_silver_block')
    event.hide('ars_ocultas:imbuement_gold_transmute')
    event.hide('starbunclemania:star_battery');
    event.hide('starbunclemania:star_sword');
    event.hide('starbunclemania:star_wand');
    
    event.hide('tomeofblood:novice_tome_of_blood');
    event.hide('tomeofblood:apprentice_tome_of_blood');
    event.hide('tomeofblood:archmage_tome_of_blood');
    
    event.hide('ars_elemental:glyph_propagator_homing');
    event.hide('ars_elemental:glyph_homing_projectile');
    event.hide('ars_elemental:debug')
    
    event.hide('ars_nouveau:glyph_animate_block');
    event.hide('ars_nouveau:creative_spell_book')
    event.hide('ars_nouveau:creative_source_jar')
    event.hide('ars_nouveau:debug')
    event.hide('ars_nouveau:rune' );
    event.hide('ars_nouveau:portal');
    event.hide('ars_nouveau:magic_fire');
    event.hide('ars_nouveau:ritual_disintegration');
    event.hide('ars_nouveau:blank_glyph');
    
    event.hide('ars_instrumentum:fake_wilden_tribute')
    
    event.hide('l2hostility:undying')
    event.hide('l2complements:space_shard')
    
    event.hide('embers:creative_ember_source')
    
    event.hide('create:handheld_worldshaper')
    event.hide('create:creative_motor')
    event.hide('create:creative_fluid_tank')
    event.hide('create:creative_crate')
    event.hide('create:creative_blaze_cake')
    
    event.hide('bloodmagic:activationcrystalcreative')
    event.hide('bloodmagic:daggerofsacrifice');
    
    event.hide('armourers_workshop:skin-library-creative')
    
    event.hide('minecraft:debug_stick')
    
    event.hide('occultism:debug_wand')
    event.hide('occultism:debug_foliot_lumberjack')
    event.hide('occultism:debug_foliot_transport_items')
    event.hide('occultism:debug_foliot_cleaner')
    event.hide('occultism:debug_foliot_trader')
    event.hide('occultism:debug_djinni_manage_machine')
    event.hide('occultism:debug_djinni_test')
    event.hide('occultism:miner_debug_unspecialized')
    
    event.hide('sophisticatedstorage:debug_tool')
    event.hide('sophisticatedbackpacks:battery_upgrade')

    event.hide('ars_trinkets:essence_lotus_3')
    event.hide('ars_trinkets:essence_lotus_4')
    event.hide('ars_trinkets:essence_lotus_5')
    event.hide('ars_trinkets:essence_lotus_6')
    event.hide('ars_trinkets:essence_lotus_7')
    event.hide('ars_trinkets:essence_lotus_8')
    event.hide('ars_trinkets:essence_lotus_9')
    event.hide('ars_trinkets:essence_lotus_10')
    event.hide('ars_trinkets:mana_stone_3')
    event.hide('ars_trinkets:mana_stone_4')
    event.hide('ars_trinkets:mana_stone_5')
    event.hide('ars_trinkets:mana_stone_5')
    event.hide('ars_trinkets:mana_stone_6')
    event.hide('ars_trinkets:mana_stone_7')
    event.hide('ars_trinkets:mana_stone_8')
    event.hide('ars_trinkets:mana_stone_9')
    event.hide('ars_trinkets:mana_stone_10')
    event.hide('ars_trinkets:monocle_1')
    event.hide('ars_trinkets:monocle_2')
    event.hide('ars_trinkets:monocle_3')
    event.hide('ars_trinkets:monocle_4')
    event.hide('ars_trinkets:monocle_5')
    event.hide('ars_trinkets:monocle_6')
    event.hide('ars_trinkets:monocle_7')
    event.hide('ars_trinkets:monocle_8')
    event.hide('ars_trinkets:monocle_9')
    event.hide('ars_trinkets:monocle_10')
    event.hide('ars_trinkets:eternal_rune')
    event.hide('ars_trinkets:life_rune_greater')
    event.hide('ars_trinkets:death_rune_greater')
    event.hide('ars_trinkets:warrior_rune_greater')
    event.hide('ars_trinkets:mage_rune_greater')
    event.hide('ars_trinkets:life_rune')
    event.hide('ars_trinkets:death_rune')
    event.hide('ars_trinkets:warrior_rune')
    event.hide('ars_trinkets:mage_rune')
    event.hide('ars_trinkets:life_rune_lesser')
    event.hide('ars_trinkets:death_rune_lesser')
    event.hide('ars_trinkets:warrior_rune_lesser')
    event.hide('ars_trinkets:mage_rune_lesser')
    event.hide('ars_trinkets:glyph_aura')
    event.hide('ars_trinkets:glyph_soul_inspector')
    event.hide('ars_trinkets:glyph_devour_soul')
    event.hide('ars_trinkets:mana_core_1')
    event.hide('ars_trinkets:mana_core_2')
    event.hide('ars_trinkets:mana_core_3')
    event.hide('ars_trinkets:mana_core_4')
    event.hide('ars_trinkets:mana_core_5')
    event.hide('ars_trinkets:mana_core_6')
    event.hide('ars_trinkets:mana_core_7')
    event.hide('ars_trinkets:mana_core_8')
    event.hide('ars_trinkets:copper_essence')
    event.hide('ars_trinkets:iron_essence')
    event.hide('ars_trinkets:silver_essence')
    event.hide('ars_trinkets:gold_essence')
    event.hide('ars_trinkets:crystal_essence')
    event.hide('ars_trinkets:green_essence')
    event.hide('ars_trinkets:red_essence')
    event.hide('ars_trinkets:white_essence')
    event.hide('ars_trinkets:yellow_essence')
    event.hide('ars_trinkets:purple_essence')
	
	event.hide('aether:locked_carved_stone')
    event.hide('aether:locked_sentry_stone')
    event.hide('aether:locked_angelic_stone')
    event.hide('aether:locked_light_angelic_stone')
    event.hide('aether:locked_hellfire_stone')
    event.hide('aether:locked_light_hellfire_stone')
    event.hide('lost_aether_content:locked_gale_stone')
    event.hide('lost_aether_content:locked_light_gale_stone')
    event.hide('ancient_aether:locked_carved_tiles')
    event.hide('ancient_aether:locked_carved_stone_mosaic')
    event.hide('ancient_aether:locked_angelic_stone_mosaic')
    event.hide('ancient_aether:locked_hellfire_stone_mosaic')
    event.hide('ancient_aether:locked_aerogetic_stone_mosaic')
    event.hide('ancient_aether:locked_gale_stone_mosaic')
    event.hide('ancient_aether:locked_wynd_sentry_stone')
    event.hide('ancient_aether:locked_aerogetic_stone')
    event.hide('ancient_aether:locked_aeronautic_stone')
    event.hide('ancient_aether:locked_corrupted_aeronautic_stone')
    event.hide('aether_redux:locked_carved_pillar')
    event.hide('aether_redux:locked_sentry_pillar')
    event.hide('aether_redux:locked_carved_base')
    event.hide('aether_redux:locked_sentry_base')
    event.hide('aether_redux:locked_runelight')
    event.hide('aether_redux:locked_polished_sentrite')
    event.hide('deep_aether:locked_nimbus_stone')
    event.hide('deep_aether:locked_light_nimbus_stone')
    event.hide('deep_aether:locked_nimbus_pillar')
    event.hide('deep_aether:locked_light_nimbus_pillar')
    event.hide('aether:trapped_carved_stone')
    event.hide('aether:trapped_sentry_stone')
    event.hide('aether:trapped_angelic_stone')
    event.hide('aether:trapped_light_angelic_stone')
    event.hide('aether:trapped_hellfire_stone')
    event.hide('aether:trapped_light_hellfire_stone')
    event.hide('lost_aether_content:trapped_gale_stone')
    event.hide('lost_aether_content:trapped_light_gale_stone')
    event.hide('ancient_aether:trapped_carved_tiles')
    event.hide('ancient_aether:trapped_aerogetic_stone')
    event.hide('ancient_aether:trapped_aeronautic_stone')
    event.hide('ancient_aether:trapped_corrupted_aeronautic_stone')
    event.hide('aether_redux:trapped_carved_pillar')
    event.hide('aether_redux:trapped_sentry_pillar')
    event.hide('aether_redux:trapped_carved_base')
    event.hide('aether_redux:trapped_sentry_base')
    event.hide('deep_aether:trapped_nimbus_stone')
    event.hide('deep_aether:trapped_light_nimbus_stone')
    event.hide('deep_aether:trapped_nimbus_pillar')
    event.hide('deep_aether:trapped_light_nimbus_pillar')
    event.hide('aether:boss_doorway_carved_stone')
    event.hide('aether:boss_doorway_sentry_stone')
    event.hide('aether:boss_doorway_angelic_stone')
    event.hide('aether:boss_doorway_light_angelic_stone')
    event.hide('aether:boss_doorway_hellfire_stone')
    event.hide('aether:boss_doorway_light_hellfire_stone')
    event.hide('lost_aether_content:boss_doorway_gale_stone')
    event.hide('lost_aether_content:boss_doorway_light_gale_stone')
    event.hide('ancient_aether:boss_doorway_carved_stone')
    event.hide('ancient_aether:boss_doorway_wynd_sentry_stone')
    event.hide('ancient_aether:boss_doorway_aerogetic_stone')
    event.hide('ancient_aether:boss_doorway_aeronautic_stone')
    event.hide('ancient_aether:boss_doorway_corrupted_aeronautic_stone')
    event.hide('aether_redux:boss_doorway_carved_pillar')
    event.hide('aether_redux:boss_doorway_sentry_pillar')
    event.hide('aether_redux:boss_doorway_carved_base')
    event.hide('aether_redux:boss_doorway_sentry_base')
    event.hide('deep_aether:boss_doorway_nimbus_stone')
    event.hide('deep_aether:boss_doorway_light_nimbus_stone')
    event.hide('deep_aether:boss_doorway_nimbus_pillar')
    event.hide('deep_aether:boss_doorway_light_nimbus_pillar')
    event.hide('aether:treasure_doorway_carved_stone')
    event.hide('aether:treasure_doorway_sentry_stone')
    event.hide('aether:treasure_doorway_angelic_stone')
    event.hide('aether:treasure_doorway_light_angelic_stone')
    event.hide('aether:treasure_doorway_hellfire_stone')
    event.hide('aether:treasure_doorway_light_hellfire_stone')
    event.hide('lost_aether_content:treasure_doorway_gale_stone')
    event.hide('lost_aether_content:treasure_doorway_light_gale_stone')
    event.hide('ancient_aether:treasure_doorway_wynd_sentry_stone')
    event.hide('ancient_aether:treasure_doorway_aerogetic_stone')
    event.hide('ancient_aether:treasure_doorway_aeronautic_stone')
    event.hide('ancient_aether:treasure_doorway_corrupted_aeronautic_stone')
    event.hide('deep_aether:treasure_doorway_nimbus_stone')
    event.hide('deep_aether:treasure_doorway_light_nimbus_stone')
    event.hide('deep_aether:treasure_doorway_nimbus_pillar')
    event.hide('deep_aether:treasure_doorway_light_nimbus_pillar')
	event.hide('aether:chest_mimic')
	
    event.hide('nameless_trinkets:ethereal_wings')
	event.hide('nameless_trinkets:fragile_cloud')
	event.hide('nameless_trinkets:sigil_of_baphomet')
	event.hide('nameless_trinkets:dubious_dust')
	event.hide('nameless_trinkets:glowing_dust')
	event.hide('nameless_trinkets:ultimate_dust')
    event.hide('skilltree:copper_ring')
    event.hide('skilltree:iron_ring')
    event.hide('skilltree:golden_ring')
    event.hide('celestial_artifacts:gold_ring')
    event.hide('celestial_artifacts:amethyst_ring')
    event.hide('celestial_artifacts:diamond_ring')
    event.hide('celestial_artifacts:netherite_ring')
    event.hide('celestial_artifacts:ring_of_life')
	event.hide('levelhearts:heart_piece')
	event.hide('levelhearts:heart_container')
	event.hide('paraglider:heart_container')
	event.hide('supplementaries:altimeter')
	event.hide('immersive_aircraft:gyrodyne')
	event.hide('relics:researching_table')
	event.hide('aether:life_shard')
	event.hide('aether_redux:veridium_lantern')
	event.hide('aether_redux:gilded_vines')
	event.hide('naturesaura:rf_converter')
	event.hide('trials:crafter')
	
	event.hide('toms_storage:ts.trim')
	event.hide('toms_storage:ts.open_crate')
	//event.hide('toms_storage:ts.inventory_cable')
	//event.hide('toms_storage:ts.inventory_cable_framed')
	//event.hide('toms_storage:ts.inventory_cable_connector')
	//event.hide('toms_storage:ts.inventory_cable_connector_framed')
	//event.hide('toms_storage:ts.inventory_cable_connector_filtered')
	event.hide('toms_storage:ts.inventory_proxy')
	//event.hide('toms_storage:ts.inventory_hopper_basic')
	event.hide('toms_storage:ts.wireless_terminal')
	event.hide('toms_storage:ts.adv_wireless_terminal')
	//event.hide('toms_storage:ts.item_filter')
	//event.hide('toms_storage:ts.polymorphic_item_filter')
	//event.hide('toms_storage:ts.tag_item_filter')
	//event.hide('toms_storage:ts.trim')
	event.hide('toms_storage:ts.level_emitter')
	event.hide('toms_storage:ts.adv_wireless_terminal')
	//event.hide('toms_storage:ts.paint_kit')	

})
JEIEvents.addItems(event => {
    event.add("minecraft:bundle")
	event.add("supplementaries:bomb_spiky")
})
