
["Dual Edge"]
	#Max stacks per level
	#Range: 0 ~ 10000
	dualEdgeStacksPerLevel = 100
	#Increased damage received per stack
	#Range: 0.0 ~ 1.0
	dualEdgeTaken = 0.01
	#Increased damage dealt per stack
	#Range: 0.0 ~ 1.0
	dualEdgeDealt = 0.01
	#Enabled
	dualEdgeEnabled = true

[Illuminate]
	#Range per level
	#Range: 2 ~ 64
	illuminateRangePerLevel = 4
	#Give Glowing to non-invisible entities
	illuminateAll = true
	#Target must be in line of sight
	illuminateLOS = false
	#Enabled
	illuminateEnabled = true

[Mobile]
	#Speed bonus amount
	#Range: 0.0 ~ 1.0
	mobileSpeed = 0.5
	#Is speed bonus flat or a percent
	mobilePercent = true
	#Enabled
	mobileEnabled = true

["Magical Blade"]
	#Percent of damage converted to magic damage
	#Range: 0.0 ~ 1.0
	magicalBladePercent = 0.15
	#Enabled
	magicalBladeEnabled = true

[Impenetrable]
	#Does max level Breaching bypass Impenetrable
	impenetrableBreachable = true
	#Enabled
	impenetrableEnabled = true

[Breaching]
	#Chance to breach per level
	#Range: 0.0 ~ 1.0
	breachingChance = 0.25
	#Enabled
	breachingEnabled = true

["Auto Block"]
	#Charges per level
	#Range: 0 ~ 10
	autoBlockCharges = 1
	#Charge rate (base, ticks)
	#Range: 0 ~ 72000
	autoBlockChargeRateBase = 400
	#Charge rate (per level, ticks)
	#Range: 0 ~ 72000
	autoBlockChargeRateLevel = 100
	#Enabled
	autoBlockEnabled = true

["Life Leech"]
	#Percent of damage converted to health
	#Range: 0.0 ~ 1.0
	lifeLeechPercent = 0.01
	#Enabled
	lifeLeechEnabled = true

[Barbs]
	#Damage per 20 ticks per level
	#Range: 0.0 ~ 100.0
	barbsDamage = 4.0
	#Enabled
	barbsEnabled = true

[Boosted]
	#Chance per level
	#Range: 0.0 ~ 1.0
	boostedChance = 0.1
	#Enabled
	boostedEnabled = true

["Climbing Gear"]
	#Enabled
	climbingGearEnabled = true

[Gluttony]
	#Enabled
	gluttonyEnabled = true

["Curse of Appetite"]
	#Enabled
	appetiteEnabled = true

[Rejuvenate]
	#Percent per level
	#Range: 0.0 ~ 1.0
	rejuvenateAmount = 0.1
	#Enabled
	rejuvenateEnabled = true

["Welding Apron"]
	#Enabled
	weldingApronEnabled = true

["Rabbits Feet"]
	#Enabled
	rabbitsFeetEnabled = true

["Moon Boots"]
	#Enabled
	moonBootsEnabled = true

[Ruthless]
	#Enabled
	ruthlessEnabled = true

[Gunner]
	#Enabled
	gunnerEnabled = true

[Seventh]
	#Enabled
	seventhEnabled = true

["Soul Mending"]
	#Enabled
	soulMendingEnabled = true

["Curse of Noodle Arms"]
	#Enabled
	noodleArmsEnabled = true

["Glass Slippers"]
	#Enabled
	glassSlippersEnabled = true

["Curse of Landmines"]
	#Enabled
	landminesEnabled = true

["Curse of Dreams"]
	#Enabled
	dreamsEnabled = true

["Night Mask"]
	#Enabled
	nightMaskEnabled = true

["Tiger Claws"]
	#Enabled
	tigerClawsEnabled = true

["Shadow Glide"]
	#Enabled
	shadowGlideEnabled = true

["One Man Army"]
	#Enabled
	oneManArmyEnabled = true

["Hawk Eyes"]
	#Enabled
	hawkEyesEnabled = true

[Safeguard]
	#Enabled
	safeguardEnabled = true

[Glare]
	#Enabled
	glareEnabled = true

[Ethereal]
	#Enabled
	etherealEnabled = true

["Magnetic Soles"]
	#Enabled
	magneticSolesEnabled = true
	#Partial Magnetic blocks enabled
	magneticSolesPartial = false

[Bolas]
	#Enabled
	bolasEnabled = true

[discovery]
	#Enabled
	discoveryEnabled = true

[Meteor]
	#Enabled
	meteorEnabled = true

["Shadow Bind"]
	#Enabled
	shadowBindEnabled = true

["Gravity Well"]
	#Enabled
	gravityWellEnabled = true

[Bash]
	#Enabled
	bashEnabled = true

["Iron Will"]
	#Enabled
	ironWillEnabled = true

["Vital Surge"]
	#Enabled
	vitalSurgeEnabled = true

["Redoubled Offensive"]
	#Enabled
	redoubledOffensiveEnabled = true

[Defiance]
	#Enabled
	defianceEnabled = true

[Fateweaver]
	#Enabled
	fateweaverEnabled = true

