#Key Adapters
#Mon Jun 22 19:53:35 EDT 2026
key.focus.lock_on=controllable.button.left_thumb_stick
keybinds.combatroll.roll=controllable.button.b
key.ars_nouveau.next_slot=
gui.xaero_open_map=controllable.button.select
key.ars_nouveau.previous_slot=
